import Head from 'next/head';
import Image from 'next/image';


import styles from '../styles/home.module.css';
import heroImg from '../../public/assets/hero.png';
import TableOne from './TablesComponents/TableOne';
import TableTwo from './TablesComponents/TableTwo';
import { useState } from 'react';


const ChartComponent: React.FC = () => {
  const [controler, setControler] = useState(0);

  const remove = () => {
    setControler(controler - 1);
  };

  const adição = () => {
    setControler(controler + 1);
  };

  function mudarTabela() {
    if (controler === 0) {
      return <TableOne />;
    } else if (controler === 1) {
      return <TableTwo />;
    } 
  }


  console.log('1', remove)
  console.log('1', adição)

  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image
            className={styles.hero}
            alt="Logo de tarefas"
            src={heroImg}
            priority
          />
        </div>
        <h1 className={styles.title}>
        Teste gráfico
        </h1>

        <div className={styles.infContent}>
          <section style={{ display: controler === 1 ? 'block' : 'none' }} onClick={remove} className={styles.box}>
            <span>Before</span>
          </section>
          <section  style={{ display: controler === 0 ? 'block' : 'none' }} onClick={adição} className={styles.box}>
            <span>Next</span>
          </section>
        </div>

        <div>
        {mudarTabela()}
        </div>
      </main>
    </div>
  );
};

export default ChartComponent;
