import Head from 'next/head';


import styles from '../styles/home.module.css';
import TableOne from './TablesComponents/TableOne';
import TableTwo from './TablesComponents/TableTwo';
import { useState } from 'react';
import TableThree from './TablesComponents/TableThree';
import { Textarea } from '@/components/textarea';


const ChartComponent: React.FC = () => {
  const [controler, setControler] = useState(0);

  const remove = () => {
    setControler(controler - 1);
  };

  const adição = () => {
    setControler(controler + 1);
  };

  function mudarTabela() {
    if (controler === 0) {
      return <TableOne />;
    } else if (controler === 1) {
      return <TableTwo />;
    } else if (controler === 2){ 
      return <TableThree />}
  }


  console.log('1', remove)
  console.log('1', adição)

  return (
    <div className={styles.container}>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
        Teste gráfico
        </h1>

        <div className={styles.infContent}>
          <section style={{ display: (controler >= 1 && controler <= 2) ? 'block' : 'none' }} onClick={remove} className={styles.box}>
            <span>Before</span>
          </section>
          <section  style={{ display: (controler >= 0 && controler <= 1) ? 'block' : 'none' }} onClick={adição} className={styles.box}>
            <span>Next</span>
          </section>
        </div>

        <div className={styles.containerTables}>
        {mudarTabela()}
        <Textarea 
        placeholder="Digite suas observações..." />
        </div>
      </main>
    </div>
  );
};

export default ChartComponent;
